/* Auto-generated by genmsg_cpp for file /home/puppeteer/ros/command_msgs/srv/speed_command.srv */
#ifndef COMMAND_MSGS_SERVICE_SPEED_COMMAND_H
#define COMMAND_MSGS_SERVICE_SPEED_COMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace command_msgs
{
template <class ContainerAllocator>
struct speed_commandRequest_ : public ros::Message
{
  typedef speed_commandRequest_<ContainerAllocator> Type;

  speed_commandRequest_()
  : robot_index(0)
  , type(0)
  , Vleft(0.0)
  , Vright(0.0)
  , Vtop(0.0)
  , div(0)
  {
  }

  speed_commandRequest_(const ContainerAllocator& _alloc)
  : robot_index(0)
  , type(0)
  , Vleft(0.0)
  , Vright(0.0)
  , Vtop(0.0)
  , div(0)
  {
  }

  typedef int32_t _robot_index_type;
  int32_t robot_index;

  typedef uint8_t _type_type;
  uint8_t type;

  typedef float _Vleft_type;
  float Vleft;

  typedef float _Vright_type;
  float Vright;

  typedef float _Vtop_type;
  float Vtop;

  typedef int32_t _div_type;
  int32_t div;


private:
  static const char* __s_getDataType_() { return "command_msgs/speed_commandRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e347a3628b1c0f3e9df84fb46b6a66b3"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "b92633d2045f118521cf5b24ea085990"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 robot_index\n\
char type\n\
float32 Vleft\n\
float32 Vright\n\
float32 Vtop\n\
int32 div\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, robot_index);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, Vleft);
    ros::serialization::serialize(stream, Vright);
    ros::serialization::serialize(stream, Vtop);
    ros::serialization::serialize(stream, div);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, robot_index);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, Vleft);
    ros::serialization::deserialize(stream, Vright);
    ros::serialization::deserialize(stream, Vtop);
    ros::serialization::deserialize(stream, div);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(robot_index);
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(Vleft);
    size += ros::serialization::serializationLength(Vright);
    size += ros::serialization::serializationLength(Vtop);
    size += ros::serialization::serializationLength(div);
    return size;
  }

  typedef boost::shared_ptr< ::command_msgs::speed_commandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::command_msgs::speed_commandRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct speed_commandRequest
typedef  ::command_msgs::speed_commandRequest_<std::allocator<void> > speed_commandRequest;

typedef boost::shared_ptr< ::command_msgs::speed_commandRequest> speed_commandRequestPtr;
typedef boost::shared_ptr< ::command_msgs::speed_commandRequest const> speed_commandRequestConstPtr;


template <class ContainerAllocator>
struct speed_commandResponse_ : public ros::Message
{
  typedef speed_commandResponse_<ContainerAllocator> Type;

  speed_commandResponse_()
  : error(false)
  {
  }

  speed_commandResponse_(const ContainerAllocator& _alloc)
  : error(false)
  {
  }

  typedef uint8_t _error_type;
  uint8_t error;


private:
  static const char* __s_getDataType_() { return "command_msgs/speed_commandResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "535618ecc8af18c0ef09ade39cc7f6c8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "b92633d2045f118521cf5b24ea085990"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool error\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, error);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, error);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(error);
    return size;
  }

  typedef boost::shared_ptr< ::command_msgs::speed_commandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::command_msgs::speed_commandResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct speed_commandResponse
typedef  ::command_msgs::speed_commandResponse_<std::allocator<void> > speed_commandResponse;

typedef boost::shared_ptr< ::command_msgs::speed_commandResponse> speed_commandResponsePtr;
typedef boost::shared_ptr< ::command_msgs::speed_commandResponse const> speed_commandResponseConstPtr;

struct speed_command
{

typedef speed_commandRequest Request;
typedef speed_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct speed_command
} // namespace command_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::command_msgs::speed_commandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e347a3628b1c0f3e9df84fb46b6a66b3";
  }

  static const char* value(const  ::command_msgs::speed_commandRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe347a3628b1c0f3eULL;
  static const uint64_t static_value2 = 0x9df84fb46b6a66b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::command_msgs::speed_commandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "command_msgs/speed_commandRequest";
  }

  static const char* value(const  ::command_msgs::speed_commandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::command_msgs::speed_commandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 robot_index\n\
char type\n\
float32 Vleft\n\
float32 Vright\n\
float32 Vtop\n\
int32 div\n\
\n\
";
  }

  static const char* value(const  ::command_msgs::speed_commandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::command_msgs::speed_commandRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::command_msgs::speed_commandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "535618ecc8af18c0ef09ade39cc7f6c8";
  }

  static const char* value(const  ::command_msgs::speed_commandResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x535618ecc8af18c0ULL;
  static const uint64_t static_value2 = 0xef09ade39cc7f6c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::command_msgs::speed_commandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "command_msgs/speed_commandResponse";
  }

  static const char* value(const  ::command_msgs::speed_commandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::command_msgs::speed_commandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool error\n\
\n\
\n\
";
  }

  static const char* value(const  ::command_msgs::speed_commandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::command_msgs::speed_commandResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::command_msgs::speed_commandRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.robot_index);
    stream.next(m.type);
    stream.next(m.Vleft);
    stream.next(m.Vright);
    stream.next(m.Vtop);
    stream.next(m.div);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct speed_commandRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::command_msgs::speed_commandResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.error);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct speed_commandResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<command_msgs::speed_command> {
  static const char* value() 
  {
    return "b92633d2045f118521cf5b24ea085990";
  }

  static const char* value(const command_msgs::speed_command&) { return value(); } 
};

template<>
struct DataType<command_msgs::speed_command> {
  static const char* value() 
  {
    return "command_msgs/speed_command";
  }

  static const char* value(const command_msgs::speed_command&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<command_msgs::speed_commandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b92633d2045f118521cf5b24ea085990";
  }

  static const char* value(const command_msgs::speed_commandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<command_msgs::speed_commandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "command_msgs/speed_command";
  }

  static const char* value(const command_msgs::speed_commandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<command_msgs::speed_commandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b92633d2045f118521cf5b24ea085990";
  }

  static const char* value(const command_msgs::speed_commandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<command_msgs::speed_commandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "command_msgs/speed_command";
  }

  static const char* value(const command_msgs::speed_commandResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COMMAND_MSGS_SERVICE_SPEED_COMMAND_H

