(cl:defpackage command_msgs-srv
  (:use )
  (:export
   "POSITION_REQUEST"
   "<POSITION_REQUEST-REQUEST>"
   "POSITION_REQUEST-REQUEST"
   "<POSITION_REQUEST-RESPONSE>"
   "POSITION_REQUEST-RESPONSE"
   "SPEED_COMMAND"
   "<SPEED_COMMAND-REQUEST>"
   "SPEED_COMMAND-REQUEST"
   "<SPEED_COMMAND-RESPONSE>"
   "SPEED_COMMAND-RESPONSE"
  ))

